### ISSUE TITLE
“Error authenticating against miniflux”

### ISSUE THREAD

**Issue by rghedin** [KevinCFechtel/FluxNews#21]
Hi! I'm trying to log in from my Miniflux instance, but Flux is throwing an error. When I try, it says `Error authenticating against miniflux`. Like this:

![Screenshot_20231218-152000_Flux News](https://github.com/KevinCFechtel/FluxNews/assets/19216581/b145f78b-5b31-4829-9ef3-042665478201)

I'm running Miniflux v2.0.48.

Any idea about what is wrong?

**Comment by KevinCFechtel** [comment]
Hello, could you please activate debug logging once and then enter the API key again? If the error message occurs again, please export the log (the button under the switch to activate debug logging) and attach it here, then I can take a look at what is going wrong.
Maybe it is a problem with the changed version endpoint of the API (was changed in version 2.0.49).

**Comment by rghedin** [comment]
```
{FluxNews}  {readConfigValues}  {Starting read config values}  {18 December 2023 03:11:40 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {18 December 2023 03:11:40 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {18 December 2023 03:11:40 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting creating DB}  {18 December 2023 03:11:40 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished creating DB}  {18 December 2023 03:11:40 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {18 December 2023 03:11:42 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {18 December 2023 03:16:11 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {18 December 2023 03:16:11 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {18 December 2023 03:16:11 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {18 December 2023 03:16:11 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {18 December 2023 03:16:11 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {18 December 2023 03:16:11 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {18 December 2023 03:37:48 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Finished checking miniflux credentials}  {18 December 2023 03:37:48 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Got unexpected response from miniflux server: 401 for checking credentials}  {18 December 2023 03:37:48 PM}  {ERROR}
```

**Comment by KevinCFechtel** [comment]
The response code 401 from miniflux says that the API key is not correct (just tested it myself with an incorrect key).
Could you generate a new API key and copy it directly from the web interface of miniflux into the app?

**Comment by rghedin** [comment]
Ops, my bad — I missed one character. Now, with the correct API key, the error message changed:

```
{FluxNews}  {readConfigValues}  {Starting read config values}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {queryNewsFromDB}  {Starting querying news from DB}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {updateNewsStatusInDB}  {Starting updating starred counter}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {renewAllNewsCount}  {Starting renewing all news count}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {queryNewsFromDB}  {Finished querying news from DB}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {updateNewsStatusInDB}  {Finished updating starred counter}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {renewAllNewsCount}  {Finished renewing all news count}  {18 December 2023 03:51:15 PM}  {INFO}
{FluxNews}  {syncNews}  {Start syncing with miniflux server.}  {18 December 2023 03:51:17 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {18 December 2023 03:51:17 PM}  {INFO}
{FluxNews}  {authCheck}  {Caught an error in authCheck function! : FormatException: Invalid radix-10 number (at character 1)
v2048
^
}  {18 December 2023 03:51:17 PM}  {ERROR}
{FluxNews}  {syncNews}  {Finished syncing with miniflux server.}  {18 December 2023 03:51:17 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {18 December 2023 03:51:20 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {18 December 2023 03:51:21 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {18 December 2023 03:51:21 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {18 December 2023 03:51:21 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {18 December 2023 03:51:21 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {18 December 2023 03:51:21 PM}  {INFO}```

**Comment by KevinCFechtel** [comment]
OK, apparently the response of the version numbers differs between the Miniflux servers. On yours, the version is indicated with a leading V...
The easiest way now would be to upgrade the miniflux version to at least 2.0.49. The version endpoint has been revised and this error should no longer occur.
In addition, I will take another look at the processing of the version numbers and correct it, but this will not be possible until tomorrow at the earliest and then it will probably take another 4 days until the update is published on F-Droid.

**Comment by KevinCFechtel** [comment]
I have fixed the bug in the current bugfix branch #20 . I am still waiting for feedback on the https only fix before the branch is published as a new release. As soon as I have published the new release, I will give you an information here. An update of the miniflux server is not necessary if you wait for the new release.

**Comment by KevinCFechtel** [comment]
I just created the new release, it should be available in the f-droid repo within the next 4-5 days (unfortunately it takes a really long time at the moment...)

**Comment by KevinCFechtel** [comment]
The release is now available, could you please test if the connection works now?

**Comment by rghedin** [comment]
It's working now, @KevinCFechtel!

However, for a friend of mine (same Miniflux server, using Flux updated version) it still not working. Here's his log:

```
{FluxNews}  {readConfigValues}  {Starting read config values}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {queryNewsFromDB}  {Starting querying news from DB}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {updateNewsStatusInDB}  {Starting updating starred counter}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {renewAllNewsCount}  {Starting renewing all news count}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {queryNewsFromDB}  {Finished querying news from DB}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {updateNewsStatusInDB}  {Finished updating starred counter}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {renewAllNewsCount}  {Finished renewing all news count}  {27 December 2023 05:10:32 PM}  {INFO}
{FluxNews}  {renewAllNewsCount}  {Starting renewing all news count}  {27 December 2023 05:10:34 PM}  {INFO}
{FluxNews}  {queryCategoriesFromDB}  {Finished querying categories from DB}  {27 December 2023 05:10:34 PM}  {INFO}
{FluxNews}  {renewAllNewsCount}  {Finished renewing all news count}  {27 December 2023 05:10:34 PM}  {INFO}
{FluxNews}  {syncNews}  {Start syncing with miniflux server.}  {27 December 2023 05:10:34 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Starting checking miniflux credentials}  {27 December 2023 05:10:34 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Miniflux v1 API Version: 2.0.51}  {27 December 2023 05:10:35 PM}  {INFO}
{FluxNews}  {checkMinifluxCredentials}  {Finished checking miniflux credentials}  {27 December 2023 05:10:35 PM}  {INFO}
{FluxNews}  {toggleNewsAsRead}  {Starting toggle news as read at miniflux server}  {27 December 2023 05:10:35 PM}  {INFO}
{FluxNews}  {toggleNewsAsRead}  {Finished toggle news as read at miniflux server}  {27 December 2023 05:10:35 PM}  {INFO}
{FluxNews}  {fetchNews}  {Starting fetching news from miniflux server}  {27 December 2023 05:10:35 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:36 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:36 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:37 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:37 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:39 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:39 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:40 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:40 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:41 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:41 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:42 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:42 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:43 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:43 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:44 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:44 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:46 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:46 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:47 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:47 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:48 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:48 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:49 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:49 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:50 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:50 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:51 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:51 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:52 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:52 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:54 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:54 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:55 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:55 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:56 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:56 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:57 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:57 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:58 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:58 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:10:59 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:10:59 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:01 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:01 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:02 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:02 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:03 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:03 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:04 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:04 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:05 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:05 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:07 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:07 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:08 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:08 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:10 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:10 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:11 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:11 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:13 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:13 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:14 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:14 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:16 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:16 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:17 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:17 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:19 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:19 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:20 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:20 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:22 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:22 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:24 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:24 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:25 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:25 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:27 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:27 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:28 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:28 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:30 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:30 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:31 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:31 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:33 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:33 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:34 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:34 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:36 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:36 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:37 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:37 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:38 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:38 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:39 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:39 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:40 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:40 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:41 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:41 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:42 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:42 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:43 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:43 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:44 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:44 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:45 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:45 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:46 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:46 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:47 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:47 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:48 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:48 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:49 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:49 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:49 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:49 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:50 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:50 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Starting read config values}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {readConfigValues}  {Finished read config values}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {readConfig}  {Starting read config}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {readConfig}  {Finished read config}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {initializeDB}  {Starting initializeDB}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {initializeDB}  {Finished initializeDB}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:51 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:52 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:52 PM}  {INFO}
{FluxNews}  {fetchNews}  {100 news fetched}  {27 December 2023 05:11:53 PM}  {INFO}
{FluxNews}  {fetchNews}  {98296 news remaining}  {27 December 2023 05:11:53 PM}  {INFO}
```

Maybe Flux is timing out due to an excessive amount of news remaining? Any other idea?

**Comment by KevinCFechtel** [comment]
Phew, that's quite a lot of news...
I don't think the problem is a timeout or anything like that. 
If I look at the logs, about 100 news items are synced per second. 
With a total of 98396 news items, this means a sync time of over 27 hours! 
I will try to recreate such a quantity of news on my system to find out where the sweet spot is for the synchronization of such a quantity of news. 
The current selection of news to be saved in the local database alone must be significantly increased...
I'll get back to you as soon as I have some info on this.

**Comment by rghedin** [comment]
That was it, @KevinCFechtel. My friend marked all as read and tried to sync again, with (way) less unread items, and now it's working again.

Maybe add an error/warning message when syncing large volumes of unread items and/or syncing takes too much time/ETA? I guess this would be helpful.

**Comment by KevinCFechtel** [comment]
Hello @rghedin ,
that's a good idea. 
I'm currently experimenting with a news list of 120,000 unread messages to speed up the sync (at least in an acceptable time frame) and to give the option of canceling the sync.
When I create a new release, I will provide more information in this issue.

**Comment by KevinCFechtel** [comment]
Hello, I have now limited the sync to 10,000 messages, otherwise the app would have taken too long to load if sync on startup was activated.
If more than 10,000 messages are available for sync, an error message indicates that the number must be reduced.
In addition, a warning is displayed from 2,000 news items that the sync may be slow due to the number of news items. There is also an option to cancel the sync.
The release has just been published and should be available in the next few days.

Best regards
Kevin

**Comment by KevinCFechtel** [comment]
Hello, I will mark this ticket as closed, if there are still errors, it is best to open a new ticket.
